# Generated by Django 5.2.13 on 2026-05-04 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSimulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Ожидает оплаты"),
                            ("processing", "Оплата обрабатывается"),
                            ("paid", "Оплачено"),
                            ("error", "Ошибка оплаты"),
                            ("canceled", "Оплата отменена"),
                        ],
                        default="processing",
                        max_length=32,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("masked_card", models.CharField(blank=True, max_length=32)),
                ("card_brand", models.CharField(blank=True, max_length=32)),
                ("holder_name", models.CharField(blank=True, max_length=120)),
                (
                    "trace_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_attempts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
