# Generated by Django 5.2.13 on 2026-05-04 14:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pickup_points", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=255)),
                ("product_image", models.URLField(blank=True)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        blank=True, db_index=True, max_length=24, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=32)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("comment", models.TextField(blank=True)),
                ("pickup_code", models.CharField(blank=True, max_length=16)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Заказ создан"),
                            ("pending_payment", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("processing", "Принят в обработку"),
                            ("assembling", "Собирается"),
                            ("sent_to_pickup", "Передан в ПВЗ"),
                            ("ready_for_pickup", "Готов к выдаче"),
                            ("received", "Получен"),
                            ("canceled", "Отменен"),
                        ],
                        default="created",
                        max_length=32,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Ожидает оплаты"),
                            ("processing", "Оплата обрабатывается"),
                            ("paid", "Оплачено"),
                            ("error", "Ошибка оплаты"),
                            ("canceled", "Оплата отменена"),
                        ],
                        default="pending_payment",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pickup_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="pickup_points.pickuppoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
