# Generated by Django 5.2.13 on 2026-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PickupPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("city", models.CharField(max_length=120)),
                ("address", models.CharField(max_length=255)),
                ("schedule", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("eta_text", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["city", "name"],
            },
        ),
    ]
